//. functionalities soap-interfaces register section

InvRegistry.RegisterInterface(TypeInfo(ITTypeSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTypeSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITTypeSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTypeSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITComponentSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITComponentSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITComponentSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITComponentSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITTProxyObjectSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTProxyObjectSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITTProxyObjectSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTProxyObjectSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITProxyObjectSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITProxyObjectSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITProxyObjectSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITProxyObjectSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITTBaseVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTBaseVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITTBaseVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTBaseVisualizationSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITBaseVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITBaseVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITBaseVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITBaseVisualizationSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITTBase2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTBase2DVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITTBase2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTBase2DVisualizationSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITBase2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITBase2DVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITBase2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITBase2DVisualizationSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITTLay2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTLay2DVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITTLay2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITTLay2DVisualizationSOAPFunctionality#%operationName%');
InvRegistry.RegisterInterface(TypeInfo(ITLay2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITLay2DVisualizationSOAPFunctionality', Encoding);
InvRegistry.RegisterDefaultSOAPAction(TypeInfo(ITLay2DVisualizationSOAPFunctionality), 'urn:FunctionalitySOAPInterface-ITLay2DVisualizationSOAPFunctionality#%operationName%');
