//. types functionalities additive Implementations (insert it into the working code)

{TTTileServerVisualizationFunctionality}

{TTileServerVisualizationFunctionality}

{TTMeasurementObjectFunctionality}

{TMeasurementObjectFunctionality}

{TTAreaNotificationServerFunctionality}

{TAreaNotificationServerFunctionality}

{TTMODELServerVisualizationFunctionality}

{TMODELServerVisualizationFunctionality}

{TTDoubleVarFunctionality}

{TDoubleVarFunctionality}

{TTInt32VarFunctionality}

{TInt32VarFunctionality}

{TTURLFunctionality}

{TURLFunctionality}

{TTPatternVisualizationFunctionality}

{TPatternVisualizationFunctionality}

{TTMapFormatObjectFunctionality}

{TMapFormatObjectFunctionality}

{TTMapFormatMapFunctionality}

{TMapFormatMapFunctionality}

{TTSPLVisualizationFunctionality}

{TSPLVisualizationFunctionality}

{TTBoolVarFunctionality}

{TBoolVarFunctionality}

{TTGeoSpaceFunctionality}

{TGeoSpaceFunctionality}

{TTUserAlertFunctionality}

{TUserAlertFunctionality}

{TTGeoGraphServerObjectFunctionality}

{TGeoGraphServerObjectFunctionality}

{TTGeoGraphServerFunctionality}

{TGeoGraphServerFunctionality}

{TTGeoCrdSystemFunctionality}

{TGeoCrdSystemFunctionality}

{TTFilterVisualizationFunctionality}

{TFilterVisualizationFunctionality}

{TTHINTVisualizationFunctionality}

{THINTVisualizationFunctionality}

{TTDetailedPictureVisualizationFunctionality}

{TDetailedPictureVisualizationFunctionality}

{TTCoVisualizationFunctionality}

{TCoVisualizationFunctionality}

{TTForumMessageFunctionality}

{TForumMessageFunctionality}

{TTForumFunctionality}

{TForumFunctionality}

{TTCUSTOMVisualizationFunctionality}

{TCUSTOMVisualizationFunctionality}

{TTOLEVisualizationFunctionality}

{TOLEVisualizationFunctionality}

{TTHTMLVisualizationFunctionality}

{THTMLVisualizationFunctionality}

{TTBZRVisualizationFunctionality}

{TBZRVisualizationFunctionality}

{TTAGIFVisualizationFunctionality}

{TAGIFVisualizationFunctionality}

{TTOrientedVIDEOVisualizationFunctionality}

{TOrientedVIDEOVisualizationFunctionality}

{TTVIDEOVisualizationFunctionality}

{TVIDEOVisualizationFunctionality}

{TTOPPVisualizationFunctionality}

{TOPPVisualizationFunctionality}

{TTMODELServerFunctionality}

{TMODELServerFunctionality}
procedure TMODELServerFunctionality.CreateNewUserByDefaultPrototype1(const NewUserName: WideString; const NewUserPassword: WideString; const NewUserFullName: WideString; const NewUserContactInfo: WideString; const Signature: WideString;  out idNewUser: integer);
begin
RemotedFunctionality.CreateNewUserByDefaultPrototype1(NewUserName,NewUserPassword,NewUserFullName,NewUserContactInfo,Signature,idNewUser);
end;


{TTCoReferenceFunctionality}

{TCoReferenceFunctionality}

{TTPositionerFunctionality}

{TPositionerFunctionality}

{TTOrientedWMFVisualizationFunctionality}

{TOrientedWMFVisualizationFunctionality}

{TTCELLVisualizationFunctionality}

{TCELLVisualizationFunctionality}

{TTEllipseVisualizationFunctionality}

{TEllipseVisualizationFunctionality}

{TTWMFVisualizationFunctionality}

{TWMFVisualizationFunctionality}

{TTPictureVisualizationFunctionality}

{TPictureVisualizationFunctionality}

{TTRoundVisualizationFunctionality}

{TRoundVisualizationFunctionality}

{TTGeodesyPointFunctionality}

{TGeodesyPointFunctionality}

{TTPrivateAreaVisualizationFunctionality}

{TPrivateAreaVisualizationFunctionality}

{TTHyperTextFunctionality}

{THyperTextFunctionality}

{TTComponentsFindServiceFunctionality}

{TComponentsFindServiceFunctionality}

{TTUsersServiceFunctionality}

{TUsersServiceFunctionality}

{TTTransportServiceFunctionality}

{TTransportServiceFunctionality}

{TTMarketServiceFunctionality}

{TMarketServiceFunctionality}

{TTTelecomServiceFunctionality}

{TTelecomServiceFunctionality}

{TTWNDVisualizationFunctionality}

{TWNDVisualizationFunctionality}

{TTMRKVisualizationFunctionality}

{TMRKVisualizationFunctionality}

{TTOrientedPictureVisualizationFunctionality}

{TOrientedPictureVisualizationFunctionality}

{TTOrientedTTFVisualizationFunctionality}

{TOrientedTTFVisualizationFunctionality}

{TTIconFunctionality}

{TIconFunctionality}

{TTMessageBoardMessageFunctionality}

{TMessageBoardMessageFunctionality}

{TTMessageBoardFunctionality}

{TMessageBoardFunctionality}

{TTHREFFunctionality}

{THREFFunctionality}

{TTQDCVisualizationFunctionality}

{TQDCVisualizationFunctionality}

{TTOffersServerFunctionality}

{TOffersServerFunctionality}

{TTSecurityComponentOperationFunctionality}

{TSecurityComponentOperationFunctionality}

{TTSecurityKeyFunctionality}

{TSecurityKeyFunctionality}

{TTSecurityFileFunctionality}

{TSecurityFileFunctionality}

{TTSecurityComponentFunctionality}

{TSecurityComponentFunctionality}

{TTMODELUserFunctionality}

{TMODELUserFunctionality}

{TTTextureFunctionality}

{TTextureFunctionality}

{TTBuffered3DVisualizationFunctionality}

{TBuffered3DVisualizationFunctionality}

{TTDATAFileFunctionality}

{TDATAFileFunctionality}

{TTCoComponentFunctionality}

{TCoComponentFunctionality}

{TTCoComponentTypeMarkerFunctionality}

{TCoComponentTypeMarkerFunctionality}

{TTCoComponentTypeFunctionality}

{TCoComponentTypeFunctionality}

{TTAddressFunctionality}

{TAddressFunctionality}

{TTTransportRouteFunctionality}

{TTransportRouteFunctionality}

{TTTransportNodeFunctionality}

{TTransportNodeFunctionality}

{TTOfferGoodsFunctionality}

{TOfferGoodsFunctionality}

{TTTLFStationTMTFunctionality}

{TTLFStationTMTFunctionality}

{TTNameFunctionality}

{TNameFunctionality}

{TTVisualizationFunctionality}

{TVisualizationFunctionality}

{TTHREFVisualizationFunctionality}

{THREFVisualizationFunctionality}

{TTTTFVisualizationFunctionality}

{TTTFVisualizationFunctionality}

{TTObjectFunctionality}

{TObjectFunctionality}

{TTLabelFunctionality}

{TLabelFunctionality}

{TTStationFunctionality}

{TStationFunctionality}

{TTMainLineFunctionality}

{TMainLineFunctionality}

{TTDescriptionFunctionality}

{TDescriptionFunctionality}

{TTImageFunctionality}

{TImageFunctionality}

{TTWellFunctionality}

{TWellFunctionality}

{TTTLFFunctionality}

{TTLFFunctionality}

{TTBoxFunctionality}

{TBoxFunctionality}

{TTCableBoxFunctionality}

{TCableBoxFunctionality}

{TTDistrLineFunctionality}

{TDistrLineFunctionality}

{TTClientFunctionality}

{TClientFunctionality}

{TTHouseFunctionality}

{THouseFunctionality}

{TTCommNodeFunctionality}

{TCommNodeFunctionality}

{TTCrossFunctionality}

{TCrossFunctionality}

{TTCaseFunctionality}

{TCaseFunctionality}

{TTStreetFunctionality}

{TStreetFunctionality}

{TTOtherObjFunctionality}

{TOtherObjFunctionality}

{TTSpanFunctionality}

{TSpanFunctionality}

{TTChanelFunctionality}

{TChanelFunctionality}

{TTHandHoldFunctionality}

{THandHoldFunctionality}

{TTLineDistFunctionality}

{TLineDistFunctionality}

{TTMuffFunctionality}

{TMuffFunctionality}

{TTOfferFunctionality}

{TOfferFunctionality}

{TTDemandFunctionality}

{TDemandFunctionality}

{TTCommLineFunctionality}

{TCommLineFunctionality}

{TTGoodsFunctionality}

{TGoodsFunctionality}

{TTCollectionFunctionality}

{TCollectionFunctionality}

